spring:
  profiles:
    active: local
  application:
    name: datecourse

---
#local
spring:
  config:
    activate:
      on-profile: local
  messages:
    basename: messages,errors
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/date_course?serverTimezone=Asia/Seoul
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      apache:
        coyote:
          http11: TRACE
server:
  servlet:
    session:
      tracking-modes: cookie

---
# test 환경 (H2 인메모리 사용)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL # H2를 MySQL 모드로 실행
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # 테스트 종료 후 DB 초기화
    show-sql: true
